### ISSUE TITLE
Improve home screen

### ISSUE THREAD

**Issue by ismail-s** [ismail-s/JTime#179]
# Issues with the current app
Atm there are a number of issues with the home screen:
- it separates one time from all the other times, when it could leave it in place and make it bold or bigger instead
- it doesn't update automatically
- only times for today are shown. This can be seen as making the home screen simpler, but also prevents using the home screen to look up times for other days

# Ideas that could be implemented
My idea for improving the home screen is as follows:
- ~~just have one big table, get rid of the big text at the top and incorporate it into the table~~ Have material design cards, each with a table, one card for each salaah type
- Table rows should have alternating colours
- The closest time (in terms of time/location) should be in bold/highlighted/larger
- update the time in bold
  - An easy way of doing this would be to refresh the results every 5 minutes
  - A better way of doing this is to somehow compute when the results would next have to be refreshed and setting a timer for then
- ~~Swipe left and right to change day , or scroll up and down~~
- Have a ... button in the toolbar at the top, with the following options available:
  -  "change location" or some better text. This should launch the place picker used in #184
  - "change date". This should open a [datepicker](//github.com/code-troopers/android-betterpickers)
- ~~If possible, code should be shared across the app and the website by compiling some kotlin code to javascript. Unless this doesn't provide enough benefit.~~ (this didn't provide enough benefit, and would have added to much extraneous code to the website than I'd like)

Note that no changes to the rest api should be necessary to do any of this.

# TODO list
- [x] Design
  - [x] ui
  - [x] functional requirements
- [x] Develop
  - [x] use [FlexboxLayout]( https://github.com/google/flexbox-layout) with `cardview`
  - [x] Alternate highlighting, highlight closest time (choose colours consistent with rest of app, follow material design guidelines if possible)
  - [x] Update times at appropriate times, taking into account when screen is switched off, screen rotations
  - [x] Scroll to closest time
  - [x] ... menu
- [x] Test (manual or unittests)
