### ISSUE TITLE
Add home screen to website

### ISSUE THREAD

**Issue by ismail-s** [ismail-s/JTime#180]
Requires getting user location. ~~Maybe should/can use https://www.npmjs.com/package/kotlin to share code with backend although would require making backend code a pure function.~~ (using this npm package would add imo too much extra code and complicate the build process substantially)

# Functional requirements
- On component being mounted, request users location. If location not granted, then display a message that this is why no nearby times can be shown. Whilst the location request is pending, display a message that user needs to allow access to location in order to see nearby times
- Once location is obtained, then behave basically the same as `HomeFragment` in the Android app does. See #179 for more details. Use `mdl-grid` to organise the cards, similar to how the `AllMasjids.vue` component works.
- The scope of this issue does _not_ cover implementing functionality to change date/location. That is to be covered in a later issue.

# TODO list
- [x] Functional requirements/design
- [x] Develop
  - [x] Layout
  - [x] Get location
  - [x] Once location obtained, display times
  - [x] Calc & display closestTime
  - [x] Calc updateTime
  - [x] set timeout based on updateTime for when to refetch and rerender
- [x] Test (unittest)
