### ISSUE TITLE
Move to Gitlab

### ISSUE THREAD

**Issue by ismail-s** [ismail-s/JTime#220]
# Discussion
## Advantages:
- All-in-one solution, atm circleci and waffle are used, both of which can be replaced with gitlab
- Migration is straightforward, main task will be to configure ci
- More open-sourcey
- Faster rate at which new features are added
- Gitlab ci allows straightforward parallellisation

## Disadvantages
- Gitlab ci sometimes/often queues builds, which could slow build times down, though this is offset somewhat by the parallellisation
- Gitlab is less popular in the open-source community, although no one else contributes anyways to this project atm, and gitlab is gaining fast in popularity

# TODO list
- [ ] Run gitlab migration
- [ ] Sort out gitlab ci
- [ ] Update description of this project, point people to gitlab repo
